///*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeJPanel.java
 *
 * Created on Apr 7, 2012, 2:14:44 AM
 */
package ui;

/**
 *
 * @author Salim
 */
public class WelcomeJPanel extends javax.swing.JPanel {

    /** Creates new form WelcomeJPanel */
    public WelcomeJPanel() {
        initComponents();
        welcomeLabel.setText("Welcome to NMT "+System.getProperty("user.name"));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 51, 0));
        welcomeLabel.setText("                   Welcome Label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(welcomeLabel)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
